Added alpaca dependency in pom.xml file
Lumberj3ck/TradingBot pull request #5
Opened 2024-12-05 16:07 UTC by timurenk0

2024-12-05 17:54 UTC, Lumberj3ck requested changes
move implementation of sell and buy methods from abstract class to new child class, called AlpacaPaper executor

2024-12-05 20:02 UTC, timurenk0 commented
> move implementation of sell and buy methods from abstract class to new child class, called AlpacaPaper executor

Why is it necessary? There should be only one buy method in the parent class and the implementation of it shouldn't change. Or am I missing something?

2024-12-05 22:13 UTC, Lumberj3ck commented
it would be not the best code practice if default implementation in abstract class has buy and sell methods hardcoded for Alpaca Trading, it's better to make a sepparate "Implementations". Because we may have different trading platforms in future. TradingExecutor shouldn't leaned towards any platform in its default sell and buy methods.

2024-12-06 12:45 UTC, Lumberj3ck commented on src/main/java/Lumberj3ck/TestExecutor.java
why TestExecutor extends AlpacaPaperExecutor instead of TradeExecutor

2024-12-06 12:46 UTC, Lumberj3ck commented on src/main/java/Lumberj3ck/Runner.java
in run method we don't want to accept only of TestExecutor and TestStrategy type, we want to accept Strategy and TradeExecutor types

2024-12-06 12:49 UTC, merged

2024-12-06 12:49 UTC, timurenk0 commented on src/main/java/Lumberj3ck/TestExecutor.java
Because TradeExecutor is abstract and we want to extend executor that we will use. In this case - alpaca. You said it that we will implement different classes for different brokers. So it makes sense to extend AlpacaPaperExecutor, instead of just abstract class

2024-12-06 12:51 UTC, timurenk0 commented on src/main/java/Lumberj3ck/Runner.java
Why do we need TestExecutor and TestStrategy then? To test them, no? So we run tests for now and in the future, when we get our code more organized, we will change them to actual strategies

2024-12-06 14:06 UTC, Lumberj3ck commented on src/main/java/Lumberj3ck/Runner.java
TestExecutor and TestStrategy is the implementations of Abstract Strategy and Abstract TradeExecutor, those are just for test and not real implementations, whilest AlpacaPaperExecutor is the real. In future we will just change our implementations which we pass to the Runner.run(), without constantly changing types we accept, because every implementation is subclass of Strategy and TradeExecutor, which accept.